### ISSUE TITLE
Display heat map layer for temperature

### ISSUE THREAD

**Issue by RickyC0626** [RickyC0626/novu-hackathon-may2023#11]
## Thought Process

Use weather forecast API to get temperature at specific latitude and longitude (https://open-meteo.com/en/docs)

Have something similar to Microsoft weather map

![ad7fd201ba6c8803f0547eac9d288047](https://github.com/RickyC0626/novu-hackathon-may2023/assets/24194862/ec82d738-d280-436a-ad03-8194d3129883)

It would probably take too many requests to get temperature at all locations to display such a heat map. It would also require a custom style. Will just display air temperature in location stats for now.

## Tasks

- [ ] Create marker on map at clicked location
- [ ] Get air temperature from coordinate of marker
- [ ] Display temperature in marker popup
